---
title: "Recommended Harvest Strategy for Southeast Alaska Red King Crab (*Paralithodes camchaticus*)"
author: "Southeast Shellfish Team"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: #pdf_document
        html_document
  #bookdown::word_document2
#bibliography: refs.bib
#csl: american-fisheries-society.csl
header-includes: \usepackage{float}

---

```{r global_options, include=FALSE, echo = FALSE, message = FALSE, warning=FALSE}
library(knitr)
opts_chunk$set(fig.width = 6, fig.height = 12, fig.pos = "H", echo = FALSE, warning = FALSE, message = FALSE,  dpi=300)
```

#Background
Management of the commercial red king crab fishery is based on the Southeast Alaska Red King Crab Management Plan (5 AAC 34.113) and policies that establishes a season that avoid sensitive life history stages of reproduction including mating and molting (November–January), restricting harvest to males only with a minimum legal-size limit of 7 inches carapace width (CW), gear restrictions, limit participation, and set annual guideline harvest levels (GHLs) based on appropriate harvest rates and results of an annual stock assessment survey. Harvest of king crab regardless of sex or size infected with parasitic barnacle species *Briarosaccus auratum* (which only infects golden king crab) and *B. regalis* (which only infects red and blue king crab) is allowed because these parasites hinder reproduction and suppress growth of king crab (Noever et al. 2016).

#Purpose
The purpose of this report is to provide the basis for a recommended update to the Southeast Alaska Red King Crab Management Plan 5 AAC 34.113.

#Management Goals and Objectives

##Harvest Strategy Revision Need

#Current Harvest Strategy

The current harvest strategy utilizes an economic threshold....

PU management plan stipulates red and blue whereas commercial stipulates red king crab only

##Commercial Fishery

**5 AAC 34.113. Southeast Alaska Red King Crab Management Plan**

* (a) The Southeast Alaska red king crab fishery shall be managed consistently with the board's "Policy on King and Tanner Crab Resource Management" (90-04-FB, March 23, 1990), adopted by this reference and accoridng to the principles set out in this section.

* (b) The department shall close an area if the abundance of various sizes of male and female crabs is inadequate to provide for a sustained harvest, or when potentially high effort precludes an orderly fishery.

* (c) The department shall close the fishery if the department's estimate of the available harvest is below the minimum threshold of 200,000 pounds of legal male red king crab.

* (d) The department shall determine an approrpiate harvest rate before the opening of the fishery. The harvest rate is the percentage of the legal males that can be harvested while providing for the long-term reproductive viability of red king crab stocks. The department shlal base the harvest rate on estimates of abundance of the various size classes of male and female crabs, and on factors affecting the reproductive viability of the stock.

* (e) The depatment shall determine the guideline harvest level before each fishing season. The guideline harvest level is the sum of the estimates of sustainable harvest for each fishing district. If stock assessment data are not available, the guideline harvest level will be based on historical fishery performance, catch, and population information. A lack of adequate information will result in conservative management.


##Personal Use Fishery

**5 AAC 77.664. Personal use king crab fishery**

* (b) Except as specificed in (e) of this section, the daily bag and possession limit is three male crab per person; if the regionwide harvestable biomass of mature red and blue king crab is below 200,00 pounds, the commissioner may, by emergency order, reduce the bag and possession limit of red and blue king crab.

#Proposed Harvest Strategy

##Commercial Fishery

**5 AAC 34.113 Southeast Alaska Red and Blue King Crab Management Plan**

* (a) The commissioner may, by emergency order, open the red and blue king crab fishery only if the depatment's preseason survey estimate of mature male red king crab biomass equals at least 50 percent of the 1979-2019 average survey estimate of mature male biomass.

* (b) If the commercial red and blue king crab fishery is open under (b) of this section, and the preseason survey estimate of mature males is

    + (1) at least 50 percent but less than 100 percent of the 1979-2019 average survey biomass estimate of mature males, the number of legal males available for harvest will be no more than than 0.1 x MMB x (MMB/MMB~1979-2019~), where MMB = the current year pre-season survey biomass estimate of mature males, and MMB~1979-2019~ = the 1979-2019 average survey biomass estimate of mature males, or 25 percent of the preseason survey biomass estimate of legal males, whichever is less. 
    
    + *(1)  at least 50 precent but less than 100 percent of the 1979-2019 average survey biomass estimate of mature males the number of legal males avaiable for harvest will be no more than 0.1 x (MMB/MMB~1979-2019~) x MMB(~regionwide~) where MMB = the current year pre-season survey biomass estimate of mature males, and MMB~1979-2019~ = the 1979-2019 average survey biomass estimate of mature males, or 25 percent of the preseason survey biomass estimate of legal males, whichever is less.*
    
    + (2) equal to or greater than the 1979-2019 average survey biomass estimate of mature males, the number of legal males availble for harvest will be no more than 10 percent of the preseason survey biomass estimate of mature males or 25 percent of the preseason survey estimate of legal males, whichever is less.

* (c) In implementing this harvest strategy, the department shall consider the reliability of abundance estimates of red king crab, the manageability of the fishery, and other factors the department determiens necessary to manage consistent with sustained yield principles, and shall use the best scientific information available and consider all sources of uncertainty as necessary to avoid overfishing.

* (d) For the purposes of this section,

    + (1) "preseason survey biomass estimate" means the
    
        - (A) population number of legal and mature male red king crab present in the time of the preason survey as estimated directy by the catch survey analysis method from annual pot survey data;
    + (2) "mature males" means all male red king crab at least 129 millimeters in length of shell
    + (3) "legal males" means all male red king crab at least seven inches or greater in width of shell. 

* (e) Except as provided in (f) of this section in Registration Area A, the holder of a CFEC permit or interim use permit for red and blue king crab may not retain more king crab in the directed fishery than the annual amount of king crab equal quota share that is specificed by the department. The department shall determine the annual ammount of king crab equal quota share by dividing the annual harvest objective by the number of CFEC permits and interim use permits eligible to fished in the fishery. The department shall use the best available information, including harvest rate and biological data, to set the total allowable catch.

* (f) If a permit holder's harvest exceeds the permit holder's equal quota share established under (e) of this section for that year, by not more than five percent, the department shall reduce the permit holder's equal quota share for the following year by the amount of the overage. The adjusted equal quota share is the permit holder's quota share for that year. If a permit holder's harvest exceeds the permit holder's equal quota share by more than five percent, the proceeds from the sale of the overage in excess of five percent shall be surrendered to the state. A permit holder may not assume that the ability to adjust a quota share under this section is an opprotunity to knowingly exceed a quota share or to exceed the equal quota share in an amount greater than five percent as such actions may be prosecuted under AS 16.05.722 or AS 16.05.723.

* (g) If a permit's holder's harvest is less than the permit holder's equal quota share established under (e) of this section for that year, the department shall increase the permit holders equal quota share only for the following year by the amount of the underage that does not exceed five percent of the equal quota share.

##Personal Use Fishery

**5 AAC 77.664. Personal use king crab fishery.**

  * (b) Except as specified in (e) of this section, the daily bag and possession limit is three male crab per person; if the pre-season survey estimate of mature male red king crab is less than 50% of the 1979-2019 average survey estimate of mature males, the commissioner may, by emergency order, reduce the bag and possession limit of red and blue king crab.


#References
